# Generated by Django 2.2 on 2019-07-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_auto_20190719_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
