# Generated by Django 2.2 on 2019-07-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_auto_20190725_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
