# Generated by Django 2.2 on 2019-07-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0004_auto_20190725_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nom_societe',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
