# Generated by Django 2.2 on 2019-07-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0006_auto_20190726_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='tarif',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
    ]
